import oracledb
import time
import streamlit as st
import pandas as pd
from datetime import datetime

from phase3.envio_email import enviar_alerta_bomba_ligada 
from phase3.servico_relatorio import enviar_relatorio_por_email

def fase3():
    conn = oracledb.connect(
        user = "RM566269",
        password = "Fiap#2025",
        dsn="ORACLE.FIAP.COM.BR:1521/ORCL"
    )
    cursor = conn.cursor()


    # Criar tabela T_Registros se não existir
    try:
        cursor.execute("""
            CREATE TABLE T_Registros (
                id_registro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                data_hora DATE,
                umidade NUMBER,
                pH NUMBER,
                fosforo NUMBER(1),
                potassio NUMBER(1),
                bomba_ativa NUMBER(1)
            )
        """)
    except oracledb.DatabaseError as e:
        pass

    #Criar tablea T_Configuracoes se não existir
    try:
        cursor.execute('''
            CREATE TABLE T_Configuracoes(
                id_config NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                limite_umidade NUMBER,
                pH_min NUMBER,
                pH_max NUMBER
            )
        ''')
    except oracledb.DatabaseError as e:
        pass

    def enviar():
        cursor.execute("""
            INSERT INTO T_Registros (data_hora, umidade, pH, fosforo, potassio, bomba_ativa)
            VALUES (:1, :2, :3, :4, :5, :6)
        """, (datetime.now(), umidade, pH, fosforo, potassio, bomba_ativa))
        conn.commit()

    st.title('Ligadior e Desligador de Bomba de Água 2.000')

    st.markdown('''
    #### Condições para ligar a bomba 💣 (de água💦)

    1. **Umidade:** menor que 30
    2. **pH:** entre 5 e 7
    3. **Minerais:** Fósforo e Potássio

    ⚠️ **Obs.** Qualquer outra configuração retornará a bomba desligada
    ```python
    if umidade < 30 and 5 <= pH <= 7 and fosforo == 1 and potassio == 1:
        bomba_ativa = 1
        st.success('Bomba **LIGADA**')
    ```
    ''')

    st.subheader("Digite os valores do Monitor Serial do Wokwi:")

    def registro(prefix="default"):
        umidade = st.slider(
            label='**Porcentagem da umidade**',
            min_value=0, max_value=100, value=50,
            key=f"{prefix}_umidade"
        )
        pH = st.slider(
            label='**Valor pH**',
            min_value=0, max_value=14, value=7,
            key=f"{prefix}_ph"
        )
        opcoes = ["Fósforo", "Potássio"]
        minerais = st.multiselect(
            '**Selecione os minerais presentes no solo**', opcoes,
            key=f"{prefix}_minerais"
        )

        st.info('Caso não haja minerais presente, não selecione nada')

        if 'Fósforo' in minerais:
            fosforo = 1
        else:
            fosforo = 0

        if 'Potássio' in minerais:
            potassio = 1
        else:
            potassio = 0

        if umidade < 30 and 5 <= pH <= 7 and fosforo == 1 and potassio == 1:
            bomba_ativa = 1
            st.success('Bomba **LIGADA**')
        else:
            bomba_ativa = 0
            st.error('Bomba **DESLIGADA**')
        
        return umidade, pH, fosforo, potassio, bomba_ativa

    # --- Início código

    umidade, pH, fosforo, potassio, bomba_ativa = registro(prefix = 'main')

    if st.button('Armazenar dados obtidos'):
        enviar()
        if bomba_ativa == 1:
            enviar_alerta_bomba_ligada(umidade, pH, fosforo, potassio)
            st.info("Alerta de 'Bomba Ligada' enviado para seu e-mail")
            time.sleep(5)
        st.rerun()

    cursor.execute("SELECT * FROM T_Registros")
    rows = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]
    df = pd.DataFrame(rows, columns=columns)
    st.dataframe(df)  

    if st.button('📧 Enviar Relatório Completo por E-mail'):
        with st.spinner('Preparando e enviando relatório...'):
            sucesso = enviar_relatorio_por_email(df)
            if sucesso:
                st.success('✅ Relatório enviado com sucesso para o seu e-mail!')
            else:
                st.error('❌ Falha ao enviar o relatório. Verifique os logs do console.')

    def delete_registro(cursor, conn):
        try:
            id_registro = st.number_input(
                label='**ID do registro que deseja deletar**',
                min_value=0,
            )
            if st.button('**DELETAR!**'):
                cursor.execute(
                    "SELECT * FROM T_Registros WHERE id_registro = :1", (id_registro,))
                if cursor.fetchone() is None:
                    st.error(f"Registro com ID {id_registro} não encontrado")
                    return
                cursor.execute(
                    "DELETE FROM T_Registros WHERE id_registro = :1", (id_registro,))
                conn.commit()
                st.success("Registro deletado com sucesso!")
        except ValueError:
            st.error("Erro: Digite um ID válido!")

    colunas = st.columns(2)

    with colunas[0]:
        st.markdown('###### Deseja deletar algum registro?')
        with st.expander("DELETAR REGISTRO", expanded = False):
            delete_registro(cursor, conn)    

    with colunas[1]:
        st.markdown('###### Deseja deletar TODOS os registros?')
        with st.expander("DELETE **TODOS** OS REGISTROS", expanded = False):
                confirm = st.checkbox('Estou ciente de que isso deletará todos os registros e desejo continuar.')
                if st.button("**DELETAR TODOS OS REGISTROS**") and confirm:
                    cursor.execute("DELETE FROM T_Registros")
                    conn.commit()
                    st.rerun()

    st.markdown('###### Deseja alterar algum registro salvo?')
    with st.expander('ALTERAÇÃO DE REGISTRO'):
        # Input do ID
        id_registro = st.number_input(
            label = 'ID do registro',
            min_value = 0,
            step = 1,
            key = 'id_edit'
        )

        # Mostra linha do ID da tabela
        if id_registro:
            linha = df[df['ID_REGISTRO'] == id_registro]
            if not linha.empty:
                st.dataframe(linha)

        umidade, pH, fosforo, potassio, bomba_ativa = registro(prefix = f"edit_{id_registro}")

        if st.button(
            'SALVAR ALTERAÇÃO',
            key = f'save_{id_registro}'):
            cursor.execute(''' 
                        update T_Registros
                        set umidade = :um,
                        pH = :ph,
                        fosforo = :fos,
                        potassio = :pot,
                        bomba_ativa = :bomba
                        where id_registro = :id 
                        ''', {
                            'um': umidade,
                            'ph': pH,
                            'fos': fosforo,
                            'pot': potassio,
                            'bomba': bomba_ativa,
                            'id': id_registro
                                })
            conn.commit()
            st.success('Registro alterado')
            time.sleep(5)
            st.rerun()