--------------------------------------------------------
--  Arquivo criado - sexta-feira-novembro-21-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_CONFIGURACOES
--------------------------------------------------------

  CREATE TABLE "RM566269"."T_CONFIGURACOES" 
   (	"ID_CONFIG" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LIMITE_UMIDADE" NUMBER, 
	"PH_MIN" NUMBER, 
	"PH_MAX" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBSPC_ALUNOS" ;
REM INSERTING into RM566269.T_CONFIGURACOES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C006214253
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM566269"."SYS_C006214253" ON "RM566269"."T_CONFIGURACOES" ("ID_CONFIG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table T_CONFIGURACOES
--------------------------------------------------------

  ALTER TABLE "RM566269"."T_CONFIGURACOES" MODIFY ("ID_CONFIG" NOT NULL ENABLE);
  ALTER TABLE "RM566269"."T_CONFIGURACOES" ADD PRIMARY KEY ("ID_CONFIG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
